OPENCONNECT_VPN_ENDPOINT="myCiscoVpnEndpoint.companyName.com"
DESTINATION_ADDRESS="myRemoteDesktopOrServerOrSshServer.companyName.com"
DESTINATION_PORT="3389"

LOCAL_DOCKER_ADDRESS="192.168.99.100"
LOCAL_DOCKER_SSH_PORT="2022"
LOCAL_LISTEN_PORT="2023"

CONTAINER_NAME="vpn_myContainerName"
IMAGE_NAME="garrett_tech:vpn_tool"

sh dockerVpnTool.sh $OPENCONNECT_VPN_ENDPOINT $DESTINATION_ADDRESS $DESTINATION_PORT $LOCAL_DOCKER_ADDRESS $LOCAL_DOCKER_SSH_PORT $LOCAL_LISTEN_PORT $CONTAINER_NAME $IMAGE_NAME